[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"

[lib]
path = "src/lib.rs"  # Explicitly specifying the location of lib.rs
crate-type = ["cdylib", "rlib"]
